name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    #Github hosted runner
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:14.3
        # Provide the username, password, and database name for postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - uses: actions/checkout@v3
    
    - name: Run migrations
      run: make migrate up

    - name: Test
      run: make test
