name: Run unit tests


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    # Github hosted runner
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:14.3
        # Provide the username, password, and database name for postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        # Need to connect service container port to Github runner (host) port
        ports:
          - 5432:5432
        
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - uses: actions/checkout@v3
    
    # Need golang-migrate installed in order to use migrateup in Makefile
    - name: Install golang-migrate
    # URL is grabbed from golang-migrate Github (specifically the Releases page to ensure the correct version is installed)
    # The binary needs to be moved to the /usr/bin folder in order for migrate command to work
    # Pipe command indicates multiline command
    # The mv command moves the file (file name found from manually unzipping the tar.gz file)
    # The which command confirms that migrate CLI is installed and ready to use
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/
        which migrate
    
    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test